# Generated by Django 3.2.8 on 2021-10-20 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='total_price',
            field=models.CharField(max_length=100),
        ),
    ]
