# Generated by Django 3.2.8 on 2021-11-03 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.RemoveField(
            model_name='address',
            name='phone',
        ),
        migrations.AlterField(
            model_name='users',
            name='create_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='last_modify_time',
            field=models.DateTimeField(),
        ),
    ]
